# Generated by Django 3.0.6 on 2020-05-09 06:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('0', 'Female'), ('1', 'Male'), ('2', 'Others')], default='Female', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nationality',
            field=django_countries.fields.CountryField(default=datetime.datetime(2020, 5, 9, 6, 32, 3, 413459, tzinfo=utc), max_length=2),
            preserve_default=False,
        ),
    ]
