# Generated by Django 3.0.6 on 2020-05-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20200509_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('0', 'Female'), ('1', 'Male'), ('2', 'Others')], max_length=10),
        ),
    ]
